services:
    app:
        build: .
        container_name: chofufesta-2024
        env_file:
            - .env
        volumes:
            - ./data:/app/data
            - ./se:/app/se
            - ./audio:/app/audio
            - /dev:/dev
        privileged: true
        stdin_open: true
        tty: true
        command: ['uv', 'run', 'src/main.py']
